# Generated by Django 3.1.4 on 2021-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car_image/default', null=True, upload_to='car_image'),
        ),
    ]
