# Generated by Django 3.1.4 on 2020-12-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='carDealerID',
            new_name='carDealer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customerID',
            new_name='customer',
        ),
    ]
