# Generated by Django 3.1.4 on 2020-12-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0002_auto_20201221_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
