# Generated by Django 3.1.4 on 2021-01-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0002_auto_20210107_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RAR.admin'),
        ),
    ]
