# Generated by Django 3.1.4 on 2021-01-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0002_auto_20210107_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='stock',
        ),
    ]
