# Generated by Django 3.1.4 on 2021-01-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
