# Generated by Django 3.1.4 on 2021-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0003_remove_car_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
