# Generated by Django 3.1.4 on 2020-12-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0003_auto_20201222_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='branchId',
            new_name='branch',
        ),
    ]
