# Generated by Django 3.1.4 on 2020-12-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0004_auto_20201223_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='carDealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RAR.cardealer'),
        ),
    ]
