# Generated by Django 3.1.4 on 2021-01-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0005_auto_20210109_1914'),
        ('RAR', '0004_reservation_total_price'),
    ]

    operations = [
    ]
