# Generated by Django 3.1.4 on 2021-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0006_merge_20210109_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='numOfDoors',
            field=models.IntegerField(choices=[(3, '3'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='numOfSeats',
            field=models.IntegerField(choices=[(2, '2'), (5, '5'), (7, '7')]),
        ),
    ]
