# Generated by Django 3.1.4 on 2020-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0006_auto_20201226_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickUpLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='returnLocation',
            field=models.CharField(max_length=100),
        ),
    ]
