# Generated by Django 3.1.4 on 2021-01-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0009_auto_20210130_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
