# Generated by Django 3.1.4 on 2021-01-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0010_auto_20210130_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(default='', max_length=8),
        ),
    ]
