# Generated by Django 3.1.4 on 2021-01-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0011_auto_20210130_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='plate',
        ),
    ]
