# Generated by Django 3.1.4 on 2021-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0014_auto_20210130_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
