# Generated by Django 3.1.4 on 2021-02-01 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0017_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 58, 4, 333082)),
        ),
    ]
