# Generated by Django 3.1.4 on 2021-02-02 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0020_auto_20210202_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 20, 11, 48, 666067)),
        ),
    ]
