# Generated by Django 3.1.4 on 2021-02-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0022_auto_20210202_2045'),
        ('RAR', '0028_auto_20210203_1916'),
    ]

    operations = [
    ]
