# Generated by Django 3.1.4 on 2020-12-07 14:54

import RAR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=RAR.models.uploaded_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('carName', models.CharField(default='', max_length=100)),
                ('userID', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('numOfSeats', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('numOfDoors', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('transmission', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('C', 'CVT')], default='M', max_length=1)),
                ('airconditioner', models.BooleanField()),
                ('price', models.IntegerField()),
                ('carStatus', models.IntegerField(choices=[(1, 'Available'), (0, 'UnAvailable')], default=1)),
                ('branchId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.IntegerField()),
                ('customerID', models.IntegerField()),
                ('carDealerID', models.IntegerField()),
                ('pickUpLocation', models.TextField()),
                ('returnLocation', models.TextField()),
                ('pickUpDate', models.DateTimeField()),
                ('returnDate', models.DateTimeField()),
                ('paymentStatus', models.BooleanField()),
            ],
        ),
    ]
