# Generated by Django 3.1.4 on 2020-12-21 11:07

import RAR.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('branch_location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=RAR.models.uploaded_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('carName', models.CharField(default='', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('airconditioner', models.BooleanField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('numOfSeats', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('numOfDoors', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('transmission', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('C', 'CVT')], default='M', max_length=1)),
                ('carStatus', models.IntegerField(choices=[(1, 'Available'), (0, 'UnAvailable')], default=1)),
                ('branchId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RAR.branch')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True)),
                ('branchId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RAR.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('licenseId', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpLocation', models.TextField()),
                ('returnLocation', models.TextField()),
                ('pickUpDate', models.DateTimeField()),
                ('returnDate', models.DateTimeField()),
                ('paymentStatus', models.BooleanField()),
                ('carDealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAR.cardealer')),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAR.car')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAR.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
