# Generated by Django 3.1.4 on 2020-12-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0003_auto_20201212_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='userID',
        ),
    ]
