# Generated by Django 3.1.4 on 2020-12-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0004_remove_car_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
