# Generated by Django 3.1.4 on 2020-12-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAR', '0005_car_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RAR.user')),
            ],
            bases=('RAR.user',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
